### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by DrizzyySP** [Discord-Transcript/NPM#2]
Command Discord.js v12:
```
const transcript = require('discord-transcript');
let channel = message.channel;

let messagecollection = message.channel.messages.fetch({
	limit: 100
});
	
let link = transcript.generate(message, messagecollection, channel);
message.channel.send(link);
```
Error:
```
(node:2392) UnhandledPromiseRejectionWarning: TypeError: Messages.forEach is not a function
    at Object.exports.generate (C:\Users\test\Desktop\Rede Flexi\node_modules\discord-transcript\lib\index.js:40:24)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Object.module.exports.run (C:\Users\test\Desktop\Rede Flexi\comandos\Desenvolvedor\test.js:188:13)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:2392) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, 
use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:2392) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by aglerr** [comment]
I have that same issues too, and I'm using discord js v12

**Comment by JustBeingAbdi** [comment]
Uhh, i have checked and it worked for me. It isn't a code issue. Which node version are y'all using?

**Comment by aglerr** [comment]
> Uhh, i have checked and it worked for me. It isn't a code issue. Which node version are y'all using?

I'm using discord.js v12.5.3 to be exact. And by the way will the embed messages and the attachment will be shown in the transcript? If so could you send me an example of the transcript? Thanks!

**Comment by aglerr** [comment]
Sorry I read the question wrong, I'm using node version 14.17.0

**Comment by JustBeingAbdi** [comment]
hmm. I will look into this. Not sure why it's giving you guys that error

**Comment by JustBeingAbdi** [comment]
Published a possible fix to this issue. Check if it is giving you guys that error now.

**Comment by aglerr** [comment]
> Published a possible fix to this issue. Check if it is giving you guys that error now.

Still got the issues, here's the errors.
`(node:116220) UnhandledPromiseRejectionWarning: TypeError: Messages.each is not a function
    at Object.exports.generate (C:\Daffa\Dream Light\New Ticket Bot\node_modules\discord-transcript\lib\index.js:38:24)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Object.exports.run (C:\Daffa\Dream Light\New Ticket Bot\commands\transcript.js:6:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:116220) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:116220) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by JustBeingAbdi** [comment]
hmm

**Comment by JustBeingAbdi** [comment]
tbh it shouldn't give errors to the both types (each & forEach) as their right types for a Discord Collection 🤔

**Comment by JustBeingAbdi** [comment]
aglerr, are you sure that in the "Messages" that it is a Discord Collection?

**Comment by aglerr** [comment]
> aglerr, are you sure that in the "Messages" that it is a Discord Collection?

I'm pretty sure, I followed the instruction on the README, and here's the coded that I used.
```js
const transcript = require('discord-transcript');

exports.run = async (client, message, args) => {

    let messageCollection = message.channel.messages.fetch({limit: 100});
    await transcript.generate(message, messageCollection, message.channel).then(async result => {
        await message.channel.send(`Link: ${result}`);
    });

};

module.exports.info = {
    name: "transcript"
};
```

**Comment by JustBeingAbdi** [comment]
hmm, i will check this out. And when i get a solution i will let you guys know. As i currently have no clue why it is giving this error.

**Comment by aglerr** [comment]
> hmm, i will check this out. And when i get a solution i will let you guys know. As i currently have no clue why it is giving this error.

Will changing the parameter to lower cases fix the issues? And also do you have Discord by any chance? We can communicate easier there and I can help you testing it.
```js
exports.generate = async function(message, Messages, Channel) -> 
          exports.generate = async function(message, messages, channel)
```

**Comment by JustBeingAbdi** [comment]
hmm, i will try. And Yes i have Discord Username: Elon_ium

**Comment by aglerr** [comment]
> hmm, i will try. And Yes i have Discord Username: Elon_ium

I need the discord tag too, mine is **aglerr#9849**, you can add me and I'll accept the friend request and we can talk there.

**Comment by JustBeingAbdi** [comment]
Opps forgot. Sent friend request. Username: Elon_ium#0791

**Comment by Mystik01** [comment]
getting same issue ^

**Comment by JustBeingAbdi** [comment]
Currently Working on fix. Will update this thread when it is fixed. If you guys have any suggestions on fix let me know. While this issue is being working on. You can use this method instead.

 message.channel.messages.fetch({limit: 10}).then(async collection => {
        channel.send("Generating transcript...");
        let link = await transcript.generate(message, collection, channel);
        message.channel.send(link)
    });
- Thanks to Aglerr

**Comment by Alexmdz77** [comment]
just add `await` here : 
`let messagecollection = await message.channel.messages.fetch({ limit: 100 });`
for me it's work fine now

**Comment by Alexmdz77** [comment]
now i have this error : 
```
(node:7556) UnhandledPromiseRejectionWarning: FetchError: request to http://143.198.247.160:3001/new?id=854344881798774804 failed, reason: socket hang up
    at ClientRequest.<anonymous> (E:\bot\node_modules\node-fetch\lib\index.js:1461:11)
    at ClientRequest.emit (events.js:315:20)
    at Socket.socketOnEnd (_http_client.js:493:9)
    at Socket.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

**Comment by JustBeingAbdi** [comment]
Discord-Transcript is going to be shutdown. and Archived.
Discord-Transcript will be implemented on a new Project i'm working on. That will be ready within the next two weeks
